### ISSUE TITLE
Help to convert

### ISSUE THREAD

**Issue by biglimp** [gusbacos/SUEWS_DB_Typology_test#7]
Ting could you help me converting this SUEWS input (v2017c) to the version we run now. I am not sure how to get it correct. I tried via the convert tool but I got error :

```python
>>>convert_table('C:/Users/xlinfr/Documents/URBANFLUXES/ESTM_Bernchmarkdata_v2017c/GBG_canyon/','C:/temp/outconvertSUEWS','2017a','2021a')
```

error:
```
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\supy\util\_converter.py", line 409, in convert_table
    SUEWS_Converter_single(
  File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\supy\util\_converter.py", line 268, in SUEWS_Converter_single
    SUEWS_Converter_file(os.path.join(toDir, fileX), actionList)
  File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\supy\util\_converter.py", line 305, in SUEWS_Converter_file
    SUEWS_Converter_action(*action)
  File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\supy\util\_converter.py", line 322, in SUEWS_Converter_action
    actionFunc[action](toFile, var, col, val)
  File "C:\Users\xlinfr\AppData\Roaming\Python\Python39\site-packages\supy\util\_converter.py", line 190, in add_var
    colNew = np.empty(dataX.shape[0], dtype=np.object)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'object'
```

[RunControl_2017c.zip](https://github.com/gusbacos/SUEWS_DB_Typology_test/files/14958854/RunControl_2017c.zip)

**Comment by sunt05** [comment]
@biglimp here you go: [2023a-save.zip](https://github.com/gusbacos/SUEWS_DB_Typology_test/files/14965640/2023a-save.zip)

The `2024.3.25.dev` version should handle it - if anything odd happens, just submit a GH issue to the SUEWS repo and I'll sort it out there.

**Comment by biglimp** [comment]
> @biglimp here you go: [2023a-save.zip](https://github.com/gusbacos/SUEWS_DB_Typology_test/files/14965640/2023a-save.zip)
> 
> The `2024.3.25.dev` version should handle it - if anything odd happens, just submit a GH issue to the SUEWS repo and I'll sort it out there.

Thanks Ting. Is this version needed for this to work converting between all versions, i.e. is this version needed for The **SUEWS Converter** in UMEP to work?
